// Shared portrait helpers used by the timeline and the details panel.

const PLACEHOLDER_PATTERN = /(^|\/)default(_dark)?\.png$/i;

export function isPlaceholderImage(source) {
  return !source || PLACEHOLDER_PATTERN.test(String(source).split('?')[0]);
}

export function getInitials(name) {
  const words = String(name || '')
    .replace(/\([^)]*\)/g, ' ')
    .split(/\s+/)
    .map((word) => word.replace(/[^\p{L}]/gu, ''))
    .filter(Boolean);
  if (!words.length) return '?';
  const first = words[0][0];
  const last = words.length > 1 ? words[words.length - 1][0] : '';
  return `${first}${last}`.toLocaleUpperCase();
}

export function illustrationsEnabled() {
  return document.getElementById('cartoonToggle')?.getAttribute('aria-pressed') === 'true';
}

export function getPortraitSource(scientist, useIllustrations = illustrationsEnabled()) {
  const cartoon = isPlaceholderImage(scientist?.cartoon) ? null : scientist.cartoon;
  const photo = isPlaceholderImage(scientist?.photo) ? null : scientist.photo;
  return (useIllustrations && cartoon) || photo || cartoon || null;
}

export function createMonogram(scientist, className) {
  const monogram = document.createElement('span');
  monogram.className = `portrait-monogram ${className || ''}`.trim();
  monogram.textContent = getInitials(scientist?.name);
  monogram.style.setProperty('--scientist-color', scientist?.color || 'var(--accent)');
  monogram.setAttribute('aria-hidden', 'true');
  return monogram;
}

// The small WebP generated by tools/generate-thumbnails.py for a portrait:
// images/a.jpg -> images/thumbs/a.webp, images/cartoons/a.png ->
// images/thumbs/cartoons/a.webp.
export function thumbnailFor(path) {
  if (!path || !path.startsWith('images/') || path.startsWith('images/thumbs/')) return path;
  return `images/thumbs/${path.slice('images/'.length).replace(/\.[^./]+$/, '.webp')}`;
}

// Returns an <img> that follows the Illustrations toggle, or a monogram when
// no verified portrait exists. Thumbnails load first; if one fails, the
// full-size original is tried, then the other portrait, then initials.
export function createPortrait(scientist, className) {
  const source = getPortraitSource(scientist);
  if (!source) return createMonogram(scientist, className);

  const image = document.createElement('img');
  image.className = className;
  image.alt = '';
  image.decoding = 'async';
  image.draggable = false;
  const photo = isPlaceholderImage(scientist.photo) ? null : scientist.photo;
  const cartoon = isPlaceholderImage(scientist.cartoon) ? null : scientist.cartoon;
  if (photo) image.dataset.originalPhoto = thumbnailFor(photo);
  if (cartoon) image.dataset.cartoonPhoto = thumbnailFor(cartoon);
  image.src = thumbnailFor(source);
  // Attempts are tracked per load, so a new Illustrations choice can fall
  // back to an original that worked before.
  image.portraitAttempts = new Set([image.getAttribute('src')]);
  image.addEventListener('error', () => {
    const attempted = image.portraitAttempts;
    const current = image.getAttribute('src');
    attempted.add(current);
    const preferred = current === image.dataset.cartoonPhoto || current === cartoon ? [cartoon, photo] : [photo, cartoon];
    const fallback = preferred.flatMap((path) => [thumbnailFor(path), path])
      .find((candidate) => candidate && !attempted.has(candidate));
    if (fallback) {
      attempted.add(fallback);
      image.src = fallback;
    } else {
      image.replaceWith(createMonogram(scientist, className));
    }
  });
  return image;
}

// Keeps every rendered portrait in step with the Illustrations toggle.
export function updatePortraitStyle(useIllustrations = illustrationsEnabled()) {
  document.querySelectorAll('img[data-original-photo], img[data-cartoon-photo]').forEach((image) => {
    const desired = (useIllustrations && image.dataset.cartoonPhoto) || image.dataset.originalPhoto || image.dataset.cartoonPhoto;
    if (desired && image.getAttribute('src') !== desired) {
      image.portraitAttempts = new Set([desired]);
      image.src = desired;
    }
  });
}
